import { api, type BaselineArm, type BaselineReport, type BaselineRun } from '../api'
import { frac, headline, pct, split, sumSplits, type Split } from '../baseline'
import { Empty } from './Explorer'
import { useRefetch } from './hooks'

const GOOD = 'var(--good)'
const BAD = 'var(--bad)'
const tone = (rate: number) => (rate >= 0.8 ? GOOD : rate >= 0.5 ? 'var(--warn)' : BAD)
const secs = (n: number) => (n ? `${Math.round(n)} s` : '—')

function Stat({ label, value, sub, color }: { label: string; value: string; sub?: string; color?: string }) {
  return (
    <div className="min-w-[120px]">
      <div className="text-[11px] uppercase tracking-wide text-[var(--muted)]">{label}</div>
      <div className="text-[19px] font-bold tabular-nums" style={{ color }}>{value}</div>
      {sub && <div className="text-[11.5px] leading-tight text-[var(--muted)]">{sub}</div>}
    </div>
  )
}

function ArmCard({ title, arm, accent, qa }: { title: string; arm?: BaselineArm; accent: string; qa: boolean }) {
  if (!arm || !arm.runs) return null
  return (
    <div className="flex-1 rounded-md border border-[var(--line)] bg-[#0b0e17] p-3" style={{ boxShadow: `inset 3px 0 0 ${accent}` }}>
      <div className="mb-2 text-[14px] font-bold">{title}</div>
      <div className="flex flex-wrap gap-x-6 gap-y-2">
        <Stat label="Builds passed" value={frac(arm.passed, arm.runs)} sub={pct(arm.pass_rate)} color={tone(arm.pass_rate)} />
        <Stat label="Time per passing build" value={secs(arm.avg_seconds_passed)} sub={`${secs(arm.avg_seconds)} over all builds`} />
        <Stat label="Tests passing at the end" value={pct(arm.test_pass_rate)} sub={`${arm.tests_passed} of ${arm.tests_passed + arm.tests_failed}`} color={tone(arm.test_pass_rate)} />
        <Stat label="Bugs caught by QA" value={qa ? String(arm.qa_bugs) : 'no QA'} sub={qa ? 'filed and routed to an owner' : 'the same tests run once, at the end'} />
        <Stat label="Review rounds that asked for changes" value={qa ? String(arm.review_requests) : 'no review'} />
        {qa && <Stat label="Contract repairs" value={String(arm.contract_repairs)} sub={`in ${arm.builds_with_repair} of ${arm.runs} builds`} />}
      </div>
    </div>
  )
}

function Bar({ s }: { s: Split }) {
  if (!s.total) return <span className="text-[var(--muted)]">—</span>
  const w = (n: number) => `${(100 * n) / s.total}%`
  return (
    <div className="flex h-[10px] w-full overflow-hidden rounded-sm bg-[#1b2236]" title={`agents ${s.agent} · rules ${s.generated} · contract repair ${s.repair}`}>
      <div style={{ width: w(s.agent), background: 'var(--accent)' }} />
      <div style={{ width: w(s.generated), background: '#56617d' }} />
      <div style={{ width: w(s.repair), background: 'var(--warn)' }} />
    </div>
  )
}

function Legend() {
  const dot = (c: string, t: string) => (
    <span className="inline-flex items-center gap-1">
      <span className="inline-block h-[9px] w-[9px] rounded-sm" style={{ background: c }} />
      {t}
    </span>
  )
  return (
    <div className="flex flex-wrap gap-x-4 text-[12px] text-[var(--muted)]">
      {dot('var(--accent)', 'written by agents')}
      {dot('#56617d', 'generated by rules (stubs, page, contract)')}
      {dot('var(--warn)', 'contract repair')}
    </div>
  )
}

function Compare({ d }: { d: BaselineReport }) {
  const { team, solo } = d.overall
  return (
    <>
      <div className="mb-2 rounded-md border border-[var(--line)] bg-[#0b0e17] px-3 py-2 text-[13px] leading-snug">{headline(team, solo)}</div>
      <div className="mb-3 flex flex-wrap gap-3">
        <ArmCard title="Team (8 employees)" arm={team} accent="var(--accent)" qa />
        <ArmCard title="Single agent (one loop)" arm={solo} accent="var(--warn)" qa={false} />
      </div>
      <table className="w-full border-collapse text-[13px]">
        <thead>
          <tr className="text-left text-[var(--muted)]">
            <th className="p-2">Goal</th>
            <th className="p-2">Team passed</th>
            <th className="p-2">Single agent passed</th>
            <th className="p-2">Team time</th>
            <th className="p-2">Single time</th>
            <th className="p-2">Tests (team / single)</th>
          </tr>
        </thead>
        <tbody>
          {d.goals.map((g) => (
            <tr key={g.key} className="border-t border-[var(--line)]" title={g.goal}>
              <td className="p-2 font-semibold">{g.key}</td>
              <td className="p-2 tabular-nums" style={{ color: tone(g.team.pass_rate) }}>{frac(g.team.passed, g.team.runs)}</td>
              <td className="p-2 tabular-nums" style={{ color: tone(g.solo.pass_rate) }}>{frac(g.solo.passed, g.solo.runs)}</td>
              <td className="p-2 tabular-nums">{secs(g.team.avg_seconds)}</td>
              <td className="p-2 tabular-nums">{secs(g.solo.avg_seconds)}</td>
              <td className="p-2 tabular-nums text-[var(--muted)]">
                {pct(g.team.test_pass_rate)} / {pct(g.solo.test_pass_rate)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="mt-2 text-[11.5px] leading-snug text-[var(--muted)]">
        The single agent has the same model, the same Architect step, the same generated stubs, page and tests (the whole suite from the start), but one loop and one context for the whole app: no Planner,
        no Reviewer, no QA, no Integrator, no contract repair, no second attempt. Its time is a failure's time too: a build that stops early is fast.
      </div>
    </>
  )
}

function Provenance({ run }: { run: BaselineRun }) {
  const a = run.authorship
  const bits = [a.spec_by && `spec: ${a.spec_by}`, a.contract_by && `contract: ${a.contract_by}`, a.plan_by && `plan: ${a.plan_by}`].filter(Boolean)
  return <span className="text-[11.5px] text-[var(--muted)]">{bits.join(' · ')}</span>
}

function Authorship({ d }: { d: BaselineReport }) {
  const all = (mode: 'team' | 'solo') => d.runs.filter((r) => r.mode === mode)
  const row = (label: string, runs: BaselineRun[]) => {
    const f = sumSplits(runs, 'functions')
    const l = sumSplits(runs, 'lines')
    return (
      <div className="flex-1 rounded-md border border-[var(--line)] bg-[#0b0e17] p-3">
        <div className="mb-1 text-[14px] font-bold">{label}</div>
        <div className="mb-1 text-[12px] text-[var(--muted)]">Functions: agents wrote {f.agent} of {f.total} ({f.total ? pct(f.agent / f.total) : '—'})</div>
        <Bar s={f} />
        <div className="mb-1 mt-2 text-[12px] text-[var(--muted)]">Lines: agents wrote {l.agent} of {l.total} ({l.total ? pct(l.agent / l.total) : '—'})</div>
        <Bar s={l} />
      </div>
    )
  }
  return (
    <>
      <div className="mb-2 flex flex-wrap items-center gap-x-6 gap-y-1">
        <span className="text-[13px] text-[var(--muted)]">App code only (database, API routes, page); tests and the preset skeleton are counted separately in each build's report.</span>
        <Legend />
      </div>
      <div className="mb-3 flex flex-wrap gap-3">
        {row('Team, all builds', all('team'))}
        {row('Single agent, all builds', all('solo'))}
      </div>
      <table className="w-full border-collapse text-[13px]">
        <thead>
          <tr className="text-left text-[var(--muted)]">
            <th className="p-2">Build</th>
            <th className="p-2">Result</th>
            <th className="p-2">Functions by agents</th>
            <th className="w-[160px] p-2">Functions</th>
            <th className="p-2">Lines by agents</th>
            <th className="w-[160px] p-2">Lines</th>
            <th className="p-2">Repair</th>
            <th className="p-2">Made by rules</th>
          </tr>
        </thead>
        <tbody>
          {d.runs.map((r) => {
            const f = split(r, 'functions')
            const l = split(r, 'lines')
            return (
              <tr key={`${r.goal_key}-${r.mode}-${r.rep}`} className="border-t border-[var(--line)]" title={r.goal}>
                <td className="p-2 font-semibold">
                  {r.goal_key} <span className="font-normal text-[var(--muted)]">{r.mode === 'team' ? 'team' : 'single'} #{r.rep}</span>
                </td>
                <td className="p-2 font-bold" style={{ color: r.ok ? GOOD : BAD }}>{r.ok ? 'PASS' : 'FAIL'}</td>
                <td className="p-2 tabular-nums">{f ? `${f.agent} / ${f.total}` : '—'}</td>
                <td className="p-2">{f && <Bar s={f} />}</td>
                <td className="p-2 tabular-nums">{l ? `${l.agent} / ${l.total}` : '—'}</td>
                <td className="p-2">{l && <Bar s={l} />}</td>
                <td className="p-2 tabular-nums">{r.contract_repairs ? `${r.contract_repairs}×` : '—'}</td>
                <td className="p-2"><Provenance run={r} /></td>
              </tr>
            )
          })}
        </tbody>
      </table>
      <div className="mt-2 text-[11.5px] leading-snug text-[var(--muted)]">
        A function counts as written by an agent when its body differs from the one the rules generated; a line counts as generated when it matches the generated file. JavaScript functions are counted
        approximately. The page is generated from the contract; an agent edits it only when a test fails.
      </div>
    </>
  )
}

/** "Team vs single agent" and "Who wrote the code": the saved results of scripts/baseline.py, as measured. */
export function BaselinePanel({ view }: { view: 'compare' | 'authorship' }) {
  const b = useRefetch(() => api.baseline(), 'baseline', 0, 0)
  if (!b.data) return <Empty text={b.error || 'Loading…'} />
  const d = b.data
  if (!d.runs.length) return <Empty text="No team-vs-single-agent runs yet. Run scripts\baseline.py to fill this tab." />
  return (
    <>
      <div className="mb-2 flex flex-wrap items-baseline gap-x-4 gap-y-1 text-[12.5px] text-[var(--muted)]">
        <span className="text-[14px] font-bold text-[var(--text)]">{view === 'compare' ? 'Team vs single agent' : 'Written by agents vs generated'}</span>
        <span>{d.runs.length} builds</span>
        {d.model && <span>{d.model}</span>}
        {d.machine && <span>{d.machine}</span>}
        {d.generated && <span>recorded {d.generated}</span>}
        {d.notes && <span>{d.notes}</span>}
      </div>
      {view === 'compare' ? <Compare d={d} /> : <Authorship d={d} />}
    </>
  )
}
