"""Who wrote the code: for a finished build, how much of the app is written by agents and how much was generated by rules.

Rules write: the stubs (names, signatures, models, routes, SQL schema), the page generated from the contract, the contract repair (functions the contract
implies), the tests, and the preset skeleton. Agents write: whatever differs from what the rules put there (function bodies, edits to the page).
The orchestrator remembers every file the rules wrote (`generated`) and every file the contract repair rewrote (`repaired`); this module compares the
final files against them, so nothing is guessed from commit messages.

Counting: Python functions by `ast` (a function is agent-written when its body differs from the generated one); lines are non-blank lines, matched
against the generated text with difflib; JavaScript functions are counted by a regex on `function name(` and `const name = (...) =>`, approximately.
"""
from __future__ import annotations

import ast
import difflib
import json
import re
from pathlib import Path

from .presets import load_preset

JS_FUNCTION = re.compile(r"^\s*(?:async\s+)?function\s+(\w+)|^\s*(?:const|let)\s+(\w+)\s*=\s*(?:async\s*)?(?:function\b|\([^)]*\)\s*=>|\w+\s*=>)")
GENERATED_TEST_DIRS = ("tests/api/", "tests/ui/", "tests/qa/", "tests/db/")
APP_SUFFIXES = (".py", ".html", ".js", ".css")


def _lines(text: str) -> list[str]:
    return [l.strip() for l in text.splitlines() if l.strip()]


def _split_lines(final: str, ref: str | None) -> tuple[int, int]:
    """(lines that came from the reference, lines that did not)."""
    fin = _lines(final)
    if not ref:
        return 0, len(fin)
    sm = difflib.SequenceMatcher(None, _lines(ref), fin, autojunk=False)
    same = sum(b.size for b in sm.get_matching_blocks())
    return same, len(fin) - same


def _py_functions(text: str) -> dict[str, str] | None:
    """Top-level and class-level function name -> a dump of its body without the docstring (None when the file does not parse)."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return None
    out: dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body[1:] if node.body and isinstance(node.body[0], ast.Expr) and isinstance(getattr(node.body[0], "value", None), ast.Constant) \
                and isinstance(node.body[0].value.value, str) else node.body
            out[node.name] = "".join(ast.dump(b) for b in body)
    return out


def _js_functions(text: str) -> dict[str, str]:
    """Function name -> its text (from its header line to the next function header): approximate, good enough to tell edited from untouched."""
    lines = text.splitlines()
    starts = [(i, (m.group(1) or m.group(2))) for i, l in enumerate(lines) if (m := JS_FUNCTION.match(l))]
    out: dict[str, str] = {}
    for n, (i, name) in enumerate(starts):
        end = starts[n + 1][0] if n + 1 < len(starts) else len(lines)
        out[name] = "\n".join(l.strip() for l in lines[i:end] if l.strip())
    return out


def _count(path: str, final: str, ref: str | None, repaired: bool) -> dict:
    """Functions and lines of one app file, split into agent / rules (stub or page) / contract repair."""
    same, diff = _split_lines(final, ref)
    c = {"path": path, "lines": same + diff, "lines_agent": diff, "lines_generated": 0 if repaired else same, "lines_repair": same if repaired else 0,
         "functions": 0, "functions_agent": 0, "functions_generated": 0, "functions_repair": 0}
    if path.endswith(".py"):
        fin, old = _py_functions(final), _py_functions(ref) if ref else {}
        if fin is None:  # a file that does not parse: every function in it is the agent's
            fin = {}
        for name, body in fin.items():
            c["functions"] += 1
            if ref and old and old.get(name) == body:
                c["functions_repair" if repaired else "functions_generated"] += 1
            else:
                c["functions_agent"] += 1
    elif path.endswith(".js"):
        fin_js, old_js = _js_functions(final), _js_functions(ref) if ref else {}
        for name, body in fin_js.items():
            c["functions"] += 1
            c["functions_generated" if old_js.get(name) == body else "functions_agent"] += 1
    return c


def _is_app_file(rel: str) -> bool:
    if rel.startswith("database/") and rel.endswith(".py"):
        return rel not in ("database/__init__.py", "database/connection.py")
    if rel.startswith("backend/api/") and rel.endswith(".py"):
        return rel != "backend/api/__init__.py"
    return rel in ("static/index.html", "static/app.js", "static/style.css")


def measure(root: Path, generated: dict[str, str], repaired: set[str], preset: str, extra: dict | None = None) -> dict:
    """The authorship report of a finished project (`.q/authorship.json`)."""
    root = Path(root)
    skeleton = load_preset(preset).skeleton
    files: list[dict] = []
    tests = {"files": 0, "lines": 0, "lines_agent": 0, "lines_generated": 0}
    skeleton_lines = 0
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.suffix not in APP_SUFFIXES:
            continue
        rel = p.relative_to(root).as_posix()
        if rel.startswith((".git/", ".worktrees/", ".q/", ".pytest_cache/", "__pycache__/")) or "/__pycache__/" in rel or "node_modules" in rel:
            continue
        final = p.read_text(encoding="utf-8", errors="replace")
        sk = skeleton / rel
        if rel.startswith("tests/"):
            same, diff = (len(_lines(final)), 0) if rel.startswith(GENERATED_TEST_DIRS) or (sk.is_file() and sk.read_text(encoding="utf-8", errors="replace") == final) else (0, len(_lines(final)))
            tests["files"] += 1
            tests["lines"] += same + diff
            tests["lines_generated"] += same
            tests["lines_agent"] += diff
        elif _is_app_file(rel):
            ref = generated.get(rel)
            if ref is None and sk.is_file():
                ref = sk.read_text(encoding="utf-8", errors="replace")  # style.css untouched = the preset's own file
            files.append(_count(rel, final, ref, rel in repaired))
        elif sk.is_file():
            skeleton_lines += len(_lines(final))
    keys = ("lines", "lines_agent", "lines_generated", "lines_repair", "functions", "functions_agent", "functions_generated", "functions_repair")
    app = {k: sum(f[k] for f in files) for k in keys}
    app["agent_share_lines"] = round(app["lines_agent"] / app["lines"], 3) if app["lines"] else 0.0
    app["agent_share_functions"] = round(app["functions_agent"] / app["functions"], 3) if app["functions"] else 0.0
    return {"app": app, "files": files, "tests": tests, "skeleton_lines": skeleton_lines, "repairs": sorted(repaired), **(extra or {})}


def save(root: Path, report: dict) -> None:
    q = Path(root) / ".q"
    q.mkdir(parents=True, exist_ok=True)
    (q / "authorship.json").write_text(json.dumps(report, indent=1), encoding="utf-8", newline="\n")
