import type { BaselineArm, BaselineRun } from './api'

export const pct = (x: number) => `${Math.round(x * 100)}%`

/** "17/18" style fraction. */
export const frac = (a: number, b: number) => `${a}/${b}`

export interface Split {
  agent: number
  generated: number
  repair: number
  total: number
}

/** How much of one build's app code was written by agents, generated by rules, or generated by the contract repair, for functions or lines. */
export function split(run: BaselineRun, by: 'functions' | 'lines'): Split | null {
  const a = run.authorship?.app
  if (!a) return null
  return by === 'functions'
    ? { agent: a.functions_agent, generated: a.functions_generated, repair: a.functions_repair, total: a.functions }
    : { agent: a.lines_agent, generated: a.lines_generated, repair: a.lines_repair, total: a.lines }
}

/** Totals of the same split over several runs. */
export function sumSplits(runs: BaselineRun[], by: 'functions' | 'lines'): Split {
  const out: Split = { agent: 0, generated: 0, repair: 0, total: 0 }
  for (const r of runs) {
    const s = split(r, by)
    if (!s) continue
    out.agent += s.agent
    out.generated += s.generated
    out.repair += s.repair
    out.total += s.total
  }
  return out
}

/** One sentence that states the result as measured, whichever way it went (never written ahead of the numbers). */
export function headline(team?: BaselineArm, solo?: BaselineArm): string {
  if (!team || !solo || !team.runs || !solo.runs) return ''
  const t = team.passed / team.runs
  const o = solo.passed / solo.runs
  const verdict = t === o ? 'Both passed the same share of the builds.' : t > o ? 'The team passed more of the builds.' : 'The single agent passed more of the builds.'
  return `Team: ${frac(team.passed, team.runs)} builds passed (${pct(team.pass_rate)}). Single agent: ${frac(solo.passed, solo.runs)} (${pct(solo.pass_rate)}). ${verdict} Same goals, same model.`
}
