"""Team vs a single agent: the same goals, the same 7B model, the same contract scaffolding and tests, built by the full team and by one agent in one loop.

    backend\.venv\Scripts\python.exe scripts\baseline.py [--reps 2] [--only calculator,todo] [--arms team,solo] [--fresh]

Every build runs in its own process (`--one`) with a time limit, so a hang is a failed build and not a stuck benchmark. After each build the result is
appended to backend/benchmarks/baseline_results.json, which the Leaderboard tab shows ("Team vs single agent" and "Who wrote the code"). Interrupted? Run it
again: builds already in the file are skipped (`--fresh` starts over).

Recorded per build: passed or not, seconds, tests passing at the end, QA bugs filed, review rounds that asked for changes, contract repairs, tokens, and the
authorship of the code (functions and lines written by agents vs generated by rules, backend/app/authorship.py). The single agent has no QA and no Reviewer,
so its bug counts are 0 by construction; what it has instead is the same complete test suite from the start.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(ROOT / "scripts"))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from goals import CHIPS  # noqa: E402

RESULTS = ROOT / "backend" / "benchmarks" / "baseline_results.json"
CHIP = dict(CHIPS)
# (key, goal): the 6 original chips, reddit and Q&A as their detailed chip goals, and a famous app by name.
GOALS = [(k, CHIP[k]) for k in ("calculator with history", "todo app", "expense tracker", "notes app", "contact book", "inventory list", "reddit replica", "Q&A forum")] \
    + [("Instagram", "Build Instagram")]
MODEL_ID = "qwen25-coder-7b"
TIME_LIMIT = 900  # seconds per build


def tests_of(summary: str) -> tuple[int, int]:
    p = re.search(r"(\d+) passed", summary or "")
    f = re.search(r"(\d+) failed", summary or "")
    e = re.search(r"(\d+) error", summary or "")
    return int(p.group(1)) if p else 0, (int(f.group(1)) if f else 0) + (int(e.group(1)) if e else 0)


def run_one(mode: str, goal: str, out: Path) -> int:
    """One build in this process; the measurements go to `out` (JSON)."""
    from build import printer
    from solo import cli_approver
    from app.baseline import SoloBuild
    from app.config import load_agents, load_env
    from app.events import EventBus
    from app.llm import LLMClient
    from app.orchestrator import Orchestrator
    from app.registry import ModelRegistry
    from app.scheduler import ModelScheduler

    load_env()
    registry = ModelRegistry.load(env={})  # local models only
    bus = EventBus()
    bus.subscribe(printer)
    scheduler = ModelScheduler(registry, emit=bus.emit)
    overrides = {a: MODEL_ID for a in [*load_agents(), "solo"]}  # the same 7B for every employee of both arms
    cls = SoloBuild if mode == "solo" else Orchestrator
    orch = cls(goal, registry, LLMClient(registry, scheduler=scheduler), bus, mode="autonomous", approver=cli_approver, local_only=True, overrides=overrides,
               max_parallel=1 if mode == "solo" else 2, polish=True, fast_live=True)
    started = time.time()
    res = orch.run()
    seconds = time.time() - started
    ev = bus.history
    reviews = [e for e in ev if e["type"] == "review_result"]
    asked = [e for e in reviews if e["verdict"] == "REQUEST_CHANGES"]
    passed, failed = tests_of(res.test_summary)
    row = {
        "mode": mode, "ok": res.ok, "seconds": round(seconds, 1), "tests": res.test_summary, "tests_passed": passed, "tests_failed": failed,
        "qa_bugs": sum(1 for e in ev if e["type"] == "bug_filed"), "review_rounds": len(reviews), "review_requests": len(asked),
        "review_items": sum(len(e["items"]) for e in asked),
        "contract_repairs": sum(1 for e in ev if e["type"] == "contract_repair" and e.get("ok")),
        "escalations": sum(1 for e in ev if e["type"] == "escalation"), "replans": sum(1 for e in ev if e["type"] == "plan_created" and e.get("replan") and e.get("reason") is None),
        "iterations": sum(s["iterations"] for s in res.agent_stats.values()), "tokens": sum(s["completion_tokens"] for s in res.agent_stats.values()),
        "problems": res.problems[:3], "slug": res.slug, "authorship": orch.authorship,
    }
    out.write_text(json.dumps(row, indent=1), encoding="utf-8")
    print(f"== {'BUILD OK' if res.ok else 'BUILD FAILED'} in {seconds:.0f}s | tests: {res.test_summary}")
    orch.ports and orch.ports.stop_all()
    return 0


def kill_tree(pid: int) -> None:
    subprocess.run(["taskkill", "/T", "/F", "/PID", str(pid)], capture_output=True)


def run_child(mode: str, key: str, goal: str, tag: str) -> dict:
    logs = ROOT / "workspace" / "_logs"
    logs.mkdir(parents=True, exist_ok=True)
    out = logs / f"baseline-{tag}.json"
    out.unlink(missing_ok=True)
    t0 = time.time()
    with open(logs / f"baseline-{tag}.txt", "w", encoding="utf-8") as log:
        p = subprocess.Popen([sys.executable, str(Path(__file__)), "--one", mode, "--goal", goal, "--out", str(out)], cwd=ROOT, stdout=log, stderr=subprocess.STDOUT,
                             env={**os.environ, "PYTHONIOENCODING": "utf-8"})
        try:
            p.wait(timeout=TIME_LIMIT)
        except subprocess.TimeoutExpired:
            kill_tree(p.pid)
            return {"mode": mode, "ok": False, "seconds": round(time.time() - t0, 1), "tests": "", "tests_passed": 0, "tests_failed": 0, "qa_bugs": 0, "review_requests": 0,
                    "contract_repairs": 0, "problems": [f"timed out after {TIME_LIMIT} s"], "authorship": {}}
    if out.is_file():
        return json.loads(out.read_text(encoding="utf-8"))
    return {"mode": mode, "ok": False, "seconds": round(time.time() - t0, 1), "tests": "", "tests_passed": 0, "tests_failed": 0, "qa_bugs": 0, "review_requests": 0,
            "contract_repairs": 0, "problems": ["the build process ended without a result"], "authorship": {}}


def load() -> dict:
    if RESULTS.is_file():
        return json.loads(RESULTS.read_text(encoding="utf-8"))
    return {}


def save(data: dict) -> None:
    RESULTS.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reps", type=int, default=2)
    ap.add_argument("--only", default="", help="comma separated goal keys (default: all 9)")
    ap.add_argument("--arms", default="team,solo")
    ap.add_argument("--fresh", action="store_true", help="forget the saved results first")
    ap.add_argument("--one", choices=["team", "solo"], help="(internal) run one build in this process")
    ap.add_argument("--goal")
    ap.add_argument("--out")
    args = ap.parse_args()
    if args.one:
        return run_one(args.one, args.goal, Path(args.out))

    keys = [k.strip() for k in args.only.split(",") if k.strip()]
    goals = [(k, g) for k, g in GOALS if not keys or k in keys]
    data = {} if args.fresh else load()
    data.setdefault("runs", [])
    data.update(model="qwen2.5-coder:7b", machine="RTX 5070 Laptop GPU (8 GB), Ollama", generated=time.strftime("%Y-%m-%d"),
                method=("Same goals, same model (qwen2.5-coder:7b for every employee), same Architect step, same contract-generated stubs, page and tests (the complete suite, edge tests included, "
                        "is in the project from the start of the single-agent build). Team: Planner, parallel engineers with a git branch each, Reviewer, QA with bug routing, Integrator, "
                        "contract repair. Single agent: ONE loop and one context for the whole app (60 iterations), no review, no QA, no integrator, no repair, no second attempt."),
                notes="Small samples (2 runs per goal and arm) on one machine: indications, not proof.")
    done = {(r["goal_key"], r["mode"], r["rep"]) for r in data["runs"]}
    arms = args.arms.split(",")
    for rep in range(1, args.reps + 1):
        for key, goal in goals:
            for mode in arms:
                if (key, mode, rep) in done:
                    continue
                tag = f"{re.sub(r'[^a-z0-9]+', '-', key.lower()).strip('-')}-{mode}-{rep}"
                row = run_child(mode, key, goal, tag)
                row.update(goal_key=key, goal=goal, rep=rep)
                data["runs"].append(row)
                data["generated"] = time.strftime("%Y-%m-%d")
                save(data)
                a = row.get("authorship", {}).get("app", {})
                print(f"{key:26} {mode:5} rep{rep} | {'PASS' if row['ok'] else 'FAIL'} | {row['seconds']:5.0f}s | tests {row['tests_passed']}/{row['tests_passed'] + row['tests_failed']} | "
                      f"bugs {row.get('qa_bugs', 0)} review {row.get('review_requests', 0)} repair {row.get('contract_repairs', 0)} | agent fn {a.get('functions_agent', '?')}/{a.get('functions', '?')} "
                      f"lines {a.get('lines_agent', '?')}/{a.get('lines', '?')}" + (f" | {row['problems'][0][:90]}" if row["problems"] else ""), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
